# Generated by Django 3.2 on 2021-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('std', models.CharField(blank=True, max_length=120, null=True)),
                ('marks', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
